version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    container_name: ci3-web
    depends_on:
      - db
    

  db:
    image: mysql:5.7
    container_name: ci3-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_nazeera
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
